name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name : Create the .ssh directory
        run : mkdir ~/.ssh && chmod 700 ~/.ssh
      - name : Install the deploy key
        run : echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy && chmod 600 ~/.ssh/deploy
      - name : Create the known hosts
        run : echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Deploy to digital ocean
        run: ssh -i ~/.ssh/deploy deployer@staging.hoteleers.com
